"""add credit_limit to accounts

Revision ID: 4b8c63300361
Revises: 53bff0f9b87d
Create Date: 2026-05-12 18:51:58.172659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8c63300361'
down_revision: Union[str, Sequence[str], None] = '53bff0f9b87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'credit_limit')
    # ### end Alembic commands ###
